name: 'DoverPiano '
favicon: null
layout_spectrum: 0.42203
typography_spectrum: 1
title: 'The Website of Patrick Dover, RPT'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#535447'
    - '#ab8b4e'
    - '#dfa879'
    - '#84968d'
    - '#6cb9c7'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.7791996207088232
purpose: []
