name: 'DoverPiano '
favicon: null
layout_spectrum: 0.99612
typography_spectrum: 0.5155
title: 'The Website of Patrick Dover, RPT'
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#C38C7A'
    - '#522A2A'
    - '#E1F2FC'
    - '#78543C'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.6510639
  rhythmicContrast: 0.75
purpose: []
