name: 'DoverPiano '
favicon: null
layout_spectrum: 0.8734
typography_spectrum: 1
title: 'The Website of Patrick Dover, RPT'
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#937448'
    - '#171810'
    - '#5e4725'
    - '#972821'
    - '#363121'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
