color:
  brandStrength: 0.493617
  saturation: 0.2957447
  brandColors:
    - '#000000'
    - '#C38C7A'
    - '#522A2A'
    - '#E1F2FC'
    - '#78543C'
  lightness: 0.6340426
  rhythmicContrast: 0.4638298
title: 'The Website of Patrick Dover, RPT'
analytics:
  facebook: null
  google: null
  twitter: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  version: null
  bucket: null
favicon: null
layout_spectrum: 0.5085106
purpose: []
name: 'DoverPiano '
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9319149
