name: 'DoverPiano '
favicon: null
layout_spectrum: 0.8787725523579866
typography_spectrum: 0.7949648858048022
title: 'The Website of Patrick Dover, RPT'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.41009107418358326
  lightness: 0.6126933107152581
  saturation: 0.7284986295271665
  rhythmicContrast: 0.7791996207088232
purpose: []
