name: 'DoverPiano '
favicon: null
layout_spectrum: 0.99368
typography_spectrum: 0.99549
title: 'The Website of Patrick Dover, RPT'
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e6f0f1'
    - '#81a1d0'
    - '#576474'
    - '#ad4000'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
